user02:
  name: -张三
  age: 23
  uno: 1001
  birth: 1999/1/16
  interes:
    - 篮球
    - rap
    - 唱跳
  score:
    english: 80.0
    math: 90.0

spring:
#指定访问路径
#  mvc:
#    static-path-pattern: /res/**

#  指定静态资源存放路径
  web:
    resources:
      static-locations: classpath:/wdm

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#设置以后项目启动必须以http://localhost:8080/aaa开始，其它请求另外再追加
#server:
#  servlet:
#    context-path: /aaa
